In [1]:
import numpy as np
import pandas as pd

<span style="color: orange; font-weight: bold; font-size:16pt">1.9. Базовые действия над матрицами</span>

**Сложение матриц**

Матрицы складываются и вычитаются поэлементно. Складывать и вычитать можно только матрицы одинакового размера.

<img src="https://lms.skillfactory.ru/assets/courseware/v1/a48adde1a4c8f50ed15ff66902b3eef9/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_53_1.png" width="300px">

<img src="https://lms.skillfactory.ru/assets/courseware/v1/3a450d5972499dae648cac1571722e42/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_53_2.png" width="400px">

**Умножение матрицы на число**

Умножение матрицы на скаляр снова аналогично векторной операции. Числовые множители также можно выносить из матрицы.

<img src="https://lms.skillfactory.ru/assets/courseware/v1/d29fc89d2e6ee0fc059391d39e2e3de6/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_53_4.png" width="800px">

**Транспонирование матриц**

При транспонировании строки матрицы записываются в столбцы и матрица переворачивается.

<img src="https://lms.skillfactory.ru/assets/courseware/v1/b02793f224687211ef4fa572f424a3dd/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_53_5_1.png" width="400px">

<img src="https://lms.skillfactory.ru/assets/courseware/v1/10e0165ffda37d49e9cab011d088bb2c/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_53_6.png" width="800px">

In [7]:
A = np.matrix('1,-5;2,2;0,3')
print(A)
print()
print(A.T)

[[ 1 -5]
 [ 2  2]
 [ 0  3]]

[[ 1  2  0]
 [-5  2  3]]


**Транспонирование симметричных матриц**

<img src="https://lms.skillfactory.ru/assets/courseware/v1/38b57c5574a5c2a9ff54140d2ab640ba/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_54.png" width="800px">

<img src="https://lms.skillfactory.ru/assets/courseware/v1/4b9a3ccd9a7944bd70bad792de63aa4a/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_54_1.png" width="800px">

**Резюме**

Матрицы складываются и вычитаются поэлементно.

Результат — матрица того же размера.

Матрицы умножаются на число поэлементно.

Результат — матрица того же размера.

При транспонировании строки превращаются в столбцы.

Размер прямоугольной матрицы меняется.

Инварианты транспонирования: симметричные матрицы.

<span style="color: orange; font-weight: bold; font-size:16pt">1.9. 1.10. --> Практика. Базовые действия над матрицами</span>

<span style="color: red; font-weight: bold; font-size:12pt">Задание 1.10.2</span>

In [11]:
Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Сonsumption = np.array([50,50,60])
Wife_Сonsumption = np.array([100,80,140])
Mother_In_Law_Сonsumption = np.array([100,20,140])

In [22]:
# Составьте матрицу Inc доходов семьи, расположив доходы мужа, жены и тещи в первый, второй и третий столбцы.
inc = np.array([Husband_Income,Wife_Income,Mother_In_Law_Income]).T
print(inc[0,0],inc[1,1],inc[2,2])


100 200 100


In [26]:
# Составьте матрицу Cons расходов семьи, расположив расходы мужа, жены и тещи в первый, второй и третий столбцы.
Cons = np.array([Husband_Сonsumption,Wife_Сonsumption,Mother_In_Law_Сonsumption]).T
print(Cons[0,2],Cons[1,1],Cons[2,0])

100 80 60


<span style="color: red; font-weight: bold; font-size:12pt">Задание 1.10.3</span>

Доходы представлены до уплаты налогов. Налоговая ставка - 13%. Вычислите матрицу доходов семьи Ивановых после уплаты налогов.

In [30]:
inc_tax = inc - (inc*0.13)
inc_tax

array([[ 87. , 130.5,  78.3],
       [191.4, 174. ,  69.6],
       [121.8, 113.1,  87. ]])

<span style="color: red; font-weight: bold; font-size:12pt">Задание 1.10.4</span>

Вычислите матрицу P, которая покажет баланс семьи Ивановых за один месяц (то есть разницу между доходами и расходами)

In [32]:
P = inc_tax-Cons
P

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

<span style="color: orange; font-weight: bold; font-size:16pt">1.11. Умножение матриц</span>

<img src="https://lms.skillfactory.ru/assets/courseware/v1/48cc0922ef79077b53aca4471d62a0de/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_55_5.png" width="800px">

<img src="https://lms.skillfactory.ru/assets/courseware/v1/804b7c2be4542096f68b8a0b477538f1/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_55_6.png" width="800px">


Операция умножения двух матриц возможна только в том случае, если число столбцов в первой матрице равно числу строк во второй.

**Размер итоговой матрицы**

Если матрица A содержит m строк, а матрица B содержит n столбцов, то результатом их умножения будет матрица С размера  m × n.

<img src="https://lms.skillfactory.ru/assets/courseware/v1/f65df3b812e8127375a24ff697f669e7/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_55_2.png" width="600px">

Умножение матриц **некоммутативно**, то есть  AB ≠ BA.

<img src="https://lms.skillfactory.ru/assets/courseware/v1/052f6e7889db85831b43cf14b502a2e1/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_55_3.png" width="600px">

<img src="https://lms.skillfactory.ru/assets/courseware/v1/df2bc6a5cd9170b4046da8bd9f8f0d62/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_55_4.png" width="800px">

Ответ: результаты умножения не только отличаются численно, но и имеют разный размер.

**Умножение вектора и матрицы** 

<img src="https://lms.skillfactory.ru/assets/courseware/v1/2a36d095ee64fd01084f3d171ef6a64a/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_55_8.png" width="800px">

<img src="https://lms.skillfactory.ru/assets/courseware/v1/413f8e7b44b7f7aaf72fce7ca3c405c9/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_55_10.png" width="800px">

<img src="https://lms.skillfactory.ru/assets/courseware/v1/73fd6b2a9d45a802b4b538d6f033a5b1/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_56.png" width="800px">

<img src="https://lms.skillfactory.ru/assets/courseware/v1/ceddf05e9091e7293a9349115e673b25/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_56_1.png" width="400px">

**Тензорное произведение векторов**

<img src="https://lms.skillfactory.ru/assets/courseware/v1/8da78293ed72c5dc06fed5eaf93ed89f/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_56_2.png" width="600px">

<img src="https://lms.skillfactory.ru/assets/courseware/v1/1139574a4ff70e02160e5ac6916a7f23/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_56_3.png" width="800px">

<img src="https://lms.skillfactory.ru/assets/courseware/v1/4ce0b03b2b0afde90da7060f91e9b623/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_56_4.png" width="600px">

In [42]:
A = np.matrix('1,-1,2,4,0;8,2,0,5,3;0,1,2,1,2')
B = np.matrix('1,0,1,1;0,0,2,-1;1,0,1,1;0,1,1,1;1,1,0,-1')
C=A*B
C[2,3]

0

<span style="color: orange; font-weight: bold; font-size:16pt">Умножение на специальные матрицы</span>

**Умножение на нулевую матрицу**


<img src="https://lms.skillfactory.ru/assets/courseware/v1/a61384f7fc646f58f31feb4d36817ce4/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_57.png" width="600px">

<img src="https://lms.skillfactory.ru/assets/courseware/v1/660d85528b31647af7fd85c67399d42d/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_57_1.png" width="800px">

Нулевая матрица играет роль нуля не только в сложении, но в умножении матриц (независимо от порядка).

**Умножение на единичную и шаровую матрицу**


<img src="https://lms.skillfactory.ru/assets/courseware/v1/15038376a6188b1ec31388433d437829/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_0003.png" width="600px">

<img src="https://lms.skillfactory.ru/assets/courseware/v1/20522d61840b0652f9e3e29edcb01625/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_57_4.png" width="800px">

Единичная матрица играет роль единицы: при умножении на неё ничего не меняется. При умножении на шаровую матрицу каждый элемент матрицы A умножился на 2, что равносильно умножению матрицы A  на число 2.

Единичная и шаровая матрицы перестановочны с любой квадратной матрицей, результат не зависит от порядка умножения.

**Умножение на диагональную матрицу**


<img src="https://lms.skillfactory.ru/assets/courseware/v1/568919b8eed29adba2c040bd09e2ae47/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_57_2.png" width="600px">

<img src="https://lms.skillfactory.ru/assets/courseware/v1/87459b217a027912860ce73109c1b81f/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_57_5.png" width="800px">


Пример 2

<img src="https://lms.skillfactory.ru/assets/courseware/v1/9da1c2384517e230729dc9960745af42/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_0005.png" width="600px">

<img src="https://lms.skillfactory.ru/assets/courseware/v1/7f2410ac742766d6608ac0e52e18bdfd/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_57_7.png" width="800px">

Диагональные матрицы неперестановочны с другими в общем случае. Но перестановочны между собой. Это их свойство будет активно использоваться при работе с матрицами ковариаций многомерных нормальных распределений.

Нулевая и единичная матрица играют роль нуля и единицы в матричном умножении.

Умножение на шаровую матрицу — то же самое, что умножение на скаляр

 Умножение на диагональную матрицу даёт растяжение каждого столбца или строки в зависимости от порядка.
 
 Диагональные матрицы коммутируют между собой.

<span style="color: orange; font-weight: bold; font-size:16pt">Делители нуля</span>

 Делители нуля — это специальные ненулевые элементы, которые дают ноль при умножении.
 
 <img src="https://lms.skillfactory.ru/assets/courseware/v1/d688da258c8ec157d4b377604d781406/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_58.png" width="800px">
 
  <img src="https://lms.skillfactory.ru/assets/courseware/v1/a1811d6a0e1760d91a0acb207cf07c79/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_58_1.png" width="800px">
  
  Матрицы А и В — примеры делителей нуля.

<span style="color: orange; font-weight: bold; font-size:16pt">1.14. Умножение и транспонирование матриця</span>

 <img src="https://lms.skillfactory.ru/assets/courseware/v1/71d801cf347455615f5a560a19d9a883/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_59.png" width="400px">

**Матрица Грама**

 Матрицей Грама системы векторов называется матрица, составленная из их скалярных произведений.
 
  <img src="https://lms.skillfactory.ru/assets/courseware/v1/3257f47d8cb4d83c724422b8264568f8/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_60_1.png" width="400px">
  
  <img src="https://lms.skillfactory.ru/assets/courseware/v1/c6ad51558b9fd49648e1682349202018/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_60_2.png" width="400px">
  
  Матрица скалярных произведений строк матрицы Х или матрица Грама для векторов (1, 1), (1, 2) и (0, -1).
 
<img src="https://lms.skillfactory.ru/assets/courseware/v1/4ee8d93b553fcc043082c18a5ff660d4/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_0002.png" width="400px">

Матрица скалярных произведений столбцов матрицы Х или матрица Грама для векторов (1, 1, 0) и (1, 2, -1).

Как видите, обе матрицы Грама симметричны. Забегая вперёд отметим, что матрица Грама системы векторов всегда имеет вещественные собственные числа и диагонализируется, а если векторы линейно независимы, то ещё и обратима. Этим мы будем пользоваться при построении и апгрейдах модели линейной регрессии.

Матрицы Х и ХТ можно умножать в любом порядке. В обоих случаях получится симметричная квадратная матрица.

<span style="color: orange; font-weight: bold; font-size:16pt">1.15. --> Практика. Умножение матриц</span>

In [5]:
# произведение матриц
A = np.random.randint(5,12,(3,3))
B = np.random.randint(-2,4,(3,3))

In [6]:
A

array([[10,  5, 10],
       [ 5,  8, 11],
       [11, 10, 10]])

In [7]:
B

array([[-2, -2,  0],
       [-2,  2,  3],
       [ 1, -1, -2]])

In [8]:
# Поэлементное умножение
A*B

array([[-20, -10,   0],
       [-10,  16,  33],
       [ 11, -10, -20]])

In [9]:
# тип np.matrix
A_m=np.matrix(A)
B_m=np.matrix(B)
print(A_m*B_m)

[[-20 -20  -5]
 [-15  -5   2]
 [-32 -12  10]]


In [10]:
# Матричное умножение
np.dot(A,B)

array([[-20, -20,  -5],
       [-15,  -5,   2],
       [-32, -12,  10]])

In [11]:
# Матричное умножение
A@B

array([[-20, -20,  -5],
       [-15,  -5,   2],
       [-32, -12,  10]])

In [12]:
# Порядок умножения AB != BA
B@A

array([[-30, -26, -42],
       [ 23,  36,  32],
       [-17, -23, -21]])

In [13]:
# Умножение прямоугольных матриц возможно не в любом порядке
A=np.random.randint(5, 12, (3,5))
B=np.random.randint(-2, 4, (5,2))
print('A:\n',A)
print('B:\n',B)

A:
 [[ 9 10  8  8  5]
 [ 7  7  8 11  7]
 [ 8  5 11  8  6]]
B:
 [[-1  0]
 [-1  0]
 [ 1  1]
 [ 1  3]
 [ 0  3]]


In [14]:
# Умножение прямоугольных матриц возможно не в любом порядке
A@B

array([[-3, 47],
       [ 5, 62],
       [ 6, 53]])

In [15]:
# Умножение прямоугольных матриц возможно не в любом порядке
B@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [16]:
# размер произведения матриц
print('shape of A:', np.shape(A))
print('shape of B:', np.shape(B))
print('shape of AB:', np.shape(A@B))

shape of A: (3, 5)
shape of B: (5, 2)
shape of AB: (3, 2)


In [17]:
# умножение на специальные матрицы
A=np.random.randint(-4, 4, (4,4))
D=np.diag([1,2,0,-1])
print('A:\n',A)
print('D:\n',D)
print('AD:\n',A@D)
print('DA:\n',D@A)

A:
 [[ 1 -1  3 -3]
 [ 3 -3 -4  0]
 [-2 -4 -1 -2]
 [-3 -3 -4  3]]
D:
 [[ 1  0  0  0]
 [ 0  2  0  0]
 [ 0  0  0  0]
 [ 0  0  0 -1]]
AD:
 [[ 1 -2  0  3]
 [ 3 -6  0  0]
 [-2 -8  0  2]
 [-3 -6  0 -3]]
DA:
 [[ 1 -1  3 -3]
 [ 6 -6 -8  0]
 [ 0  0  0  0]
 [ 3  3  4 -3]]


In [18]:
# умножение на одномерный массив numpy
A=np.array([[1,0,1],[1,1,1]])
b=np.array([-3,4,5])
A@b

array([2, 6])

In [23]:
# матрица Грама ортогональной системы векторов
x=np.array([1,1,1])
y=np.array([1,0,-1])
z=np.array([-1,2,-1])
A=np.array([x,y,z])
print (A, type(A))

[[ 1  1  1]
 [ 1  0 -1]
 [-1  2 -1]] <class 'numpy.ndarray'>


In [24]:
# матрица Грама ортогональной системы векторов
A@A.T
# Система векторов xyz является ортогональной

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 6]])

In [25]:
# матрица Грама ортонормированной системы векторов
x_norm=x/np.linalg.norm(x)
y_norm=y/np.linalg.norm(y)
z_norm=z/np.linalg.norm(z)
A_norm=np.array([x_norm,y_norm,z_norm])
print (A_norm, type(A_norm))

[[ 0.57735027  0.57735027  0.57735027]
 [ 0.70710678  0.         -0.70710678]
 [-0.40824829  0.81649658 -0.40824829]] <class 'numpy.ndarray'>


In [26]:
# матрица Грама ортонормированной системы векторов
A_norm@A_norm.T

array([[ 1.00000000e+00, -1.77961928e-17,  1.66584120e-17],
       [-1.77961928e-17,  1.00000000e+00, -2.45142679e-17],
       [ 1.66584120e-17, -2.45142679e-17,  1.00000000e+00]])

In [27]:
# ортонормированные системы рулят! :)
np.round(A_norm@A_norm.T,1)

array([[ 1., -0.,  0.],
       [-0.,  1., -0.],
       [ 0., -0.,  1.]])

<span style="color: red; font-weight: bold; font-size:12pt"> Задача 1. Условие</span>

Даны матрица A и вектор x .

In [28]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])
print(A)
print(x)

[[ 5 -1  3  1  2]
 [-2  8  5 -1  1]]
[1 2 3 4 5]


In [32]:
# Найдите произведение матрицы A и вектора x  в том порядке, в котором их можно умножить.
A@x

array([26, 30])

<span style="color: red; font-weight: bold; font-size:12pt"> Задача 2. Условие</span>


In [37]:
A=np.array( [ [1,9,8,5] , [3,6,3,2] , [3,3,3,3], [0,2,5,9], [4,4,1,2] ] )
B=np.array( [ [1,-1,0,1,1] , [-2,0,2,-1,1] ] )
print(f'A:\n {np.shape(A)}')
print(f'B:\n {np.shape(B)}')

A:
 (5, 4)
B:
 (2, 5)


In [42]:
# Найдите произведение матриц A и B в том порядке, в котором их можно умножить.
B@A

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

<span style="color: red; font-weight: bold; font-size:12pt"> Задача 3. Условие</span>


In [44]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

In [47]:
# Найдите матрицу Грама системы векторов 

sys = np.array([x,y,z])
sys@sys.T


array([[22,  3,  0],
       [ 3,  7,  0],
       [ 0,  0,  3]])

<span style="color: red; font-weight: bold; font-size:12pt"> Задача 4. Условие</span>

В салоне красоты «Феи ножниц» работает 8 стилистов: Аня, Борис, Вика, Галя, Дима, Егор, Женя и Юра.

В dataframe Count_DF содержится информация по количеству услуг, оказанных каждым стилистом за апрель.

В dataframe Price_DF содержится информация по стоимости услуг у каждого стилиста в тысячах рублей.

In [76]:
count_df = pd.DataFrame({'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
                                'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
                                'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
                              'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
                                'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])
price_df = pd.DataFrame({'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
                                'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
                                'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
                              'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
                                'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])

In [63]:
count = count_df.values
price = price_df.values

In [74]:
#  Найдите вектор выручки Бориса. V1
b_c = count[1:2]
b_p = price[1:2]

b_c*b_p


array([[ 3.6, 52.5,  3. , 25. ,  6. ]])

In [68]:
# V2
boris_inc = count[1]*price[1]
boris_inc

array([ 3.6, 52.5,  3. , 25. ,  6. ])

In [82]:
#Найдите вектор прибыли салона по стилистам, если за каждую услугу стилисты платят определенную комиссию салону.

# Вектор комиссий com = [0.2, 0.2, 0.3, 0.1, 0.1]
com = [0.2, 0.2, 0.3, 0.1, 0.1]
summa = count*price
summa@com

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

In [85]:
# Найдите вектор прибыли стилистов
summa@(np.ones(5)-com)

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

In [86]:
styl = (price*count)@(np.ones(5)-com)

In [87]:
styl

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

<span style="color: orange; font-weight: bold; font-size:16pt">1.16. Обратная матрица</span>

<img src="https://lms.skillfactory.ru/assets/courseware/v1/676f50037d58ec7c52b561b59ca254f3/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_52_10.png" width="400px">

<img src="https://lms.skillfactory.ru/assets/courseware/v1/cea7d817f44b427ae34a8146a1281a8a/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_61_4.png" width="600px">

Перед нами встаёт задача научиться подбирать такую матрицу, которая даст в произведении с исходной единичную.

<img src="https://lms.skillfactory.ru/assets/courseware/v1/ffd1b918b252b083c3d7eaf8df852096/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_61_5.png" width="400px">

Умножим справа:

<img src="https://lms.skillfactory.ru/assets/courseware/v1/c190979eaba857e6a6c497ae91f381ff/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_61_7.png" width="300px">

Умножим слева:

<img src="https://lms.skillfactory.ru/assets/courseware/v1/ec336f28d2385d8864f52e24356aa391/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_61_8.png" width="300px">

Мы ответили на наш первый вопрос:
<img src="https://lms.skillfactory.ru/assets/courseware/v1/403c707dc39b1a91404cfad2df03e0fc/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_61_6.png" width="300px">

<img src="https://lms.skillfactory.ru/assets/courseware/v1/b86395dbd33746495f02f97e3f607cd4/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_62.png" width="400px">

Решение:

<img src="https://lms.skillfactory.ru/assets/courseware/v1/c6d75d48703c651285ba860523585388/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_62_1.png" width="800px">


<img src="https://lms.skillfactory.ru/assets/courseware/v1/3910c0399527f070b81c9e104cde2971/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_62_2.png" width="400px">

<span style="color: orange; font-weight: bold; font-size:16pt">1.17. Определитель матрицы</span>

 Определитель матрицы — это число, специальная числовая характеристика квадратных матриц, которая является своего рода мерой вырожденности матрицы и для размерности 2 × 2 вычисляется по следующему правилу:
 
 <img src="https://lms.skillfactory.ru/assets/courseware/v1/ab4865170852c9aafa62cff53433bb3c/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_63_3.png" width="400px">

Если det (A) = 0, то:

матрица А вырожденная;

у матрицы А не существует обратной;

столбцы и строки матрицы А линейно зависимы.

In [92]:
A = np.matrix('2,0,0;0,1,0;0,0,4')
print(np.linalg.det(A))
A_1 = np.linalg.inv(A)
print(np.linalg.det(A_1))

7.999999999999998
0.12500000000000003


<span style="color: orange; font-weight: bold; font-size:16pt">1.17. Линейная (не)зависимость</span>

***Как определить при помощи ранга, являются ли векторы линейно зависимыми***

Ранг матрицы — количество линейно независимых столбцов.

Ранг системы векторов — размерность этой системы. 

После преобразований матрицы к ступенчатому виду ранг равен количеству ступенек.

 <img src="https://lms.skillfactory.ru/assets/courseware/v1/5776b5add03dab6568992bf3cc7a283e/asset-v1:Skillfactory+DST-PRO+15APR2020+type@asset+block/MAT_1_unit_010.png" width="400px">

Ранг системы векторов равен количеству линейно независимых векторов, т.е. размерности всей системы.

Чтобы исследовать систему векторов на линейную зависимость / независимость с помощью ранга, достаточно записать эти векторы в матрицу по столбцам и найти ранг полученной матрицы. Ранг будет равен количеству линейно независимых векторов в системе.

Базис — максимальная линейно независимая подсистема векторов.

В системе векторов можно выбрать ровно столько линейно независимых векторов, какой у нее ранг.

Базис матрицы — максимальная линейно независимая подсистема столбцов матрицы.




<span style="color: orange; font-weight: bold; font-size:16pt">1.20. --> Практика. Обратная матрица, ранг, определитель</span>

In [99]:
# обратная матрица - все ок
A1=np.array([[1,2,3],[4,5,6],[7,8,10]])
print('A1:\n',A1)

A1:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]


In [100]:
print('rk(A3):\n',np.linalg.matrix_rank(A1))

rk(A3):
 3


In [101]:
# обратная матрица - все ок
A1_inv=np.linalg.inv(A1)
print('A1 inversed:\n',A1_inv)


A1 inversed:
 [[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]


In [102]:
# обратная матрица - все ок
print('A1 @ A1 inversed=E check:\n',A1@A1_inv,1)
print(np.round(A1@A1_inv,1))
print('check OK')

A1 @ A1 inversed=E check:
 [[ 1.00000000e+00 -4.44089210e-16 -1.11022302e-16]
 [ 4.44089210e-16  1.00000000e+00 -2.22044605e-16]
 [ 4.44089210e-16  8.88178420e-16  1.00000000e+00]] 1
[[ 1. -0. -0.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]
check OK


In [103]:
# обратная матрица - вырожденный случай
A2=np.array([[1,2,3],[4,5,6],[1,2,3]])
print('A2:\n',A2)

A2:
 [[1 2 3]
 [4 5 6]
 [1 2 3]]


In [104]:
# обратная матрица - вырожденный случай
print('rk(A3):\n',np.linalg.matrix_rank(A2))

rk(A3):
 2


In [106]:
# обратная матрица - вырожденный случай
#np.linalg.inv(A2)

In [107]:
# обратная матрица - magic
A3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print('A3:\n',A3)

A3:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [108]:
# обратная матрица - magic
print('rk(A3):\n',np.linalg.matrix_rank(A3))

rk(A3):
 2


In [109]:
# обратная матрица - magic
print('A3 inversed:\n',np.linalg.inv(A3))

A3 inversed:
 [[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [110]:
# обратная матрица - magic
print('A3 @ A3 inversed = E check:\n',A3@np.linalg.inv(A3))
print('check failed')

A3 @ A3 inversed = E check:
 [[ 0.   1.  -0.5]
 [ 0.   2.  -1. ]
 [ 0.   3.   2.5]]
check failed


In [111]:
print('det(A1)):\n',np.linalg.det(A1))
print('det(A2)):\n',np.linalg.det(A2))
print('det(A3)):\n',np.linalg.det(A3))

det(A1)):
 -3.000000000000001
det(A2)):
 0.0
det(A3)):
 -9.51619735392994e-16


<span style="color: red; font-weight: bold; font-size:12pt"> Задача 1. Условие</span>

In [113]:
A=np.array( [[ 8 , 6 ,11],[ 7 , 5 , 9],[ 6 ,10,  6]])

In [115]:
# Найдите обратную матрицу к матрице А.
inv = np.linalg.inv(A)
inv

array([[-1.875  ,  2.3125 , -0.03125],
       [ 0.375  , -0.5625 ,  0.15625],
       [ 1.25   , -1.375  , -0.0625 ]])

<span style="color: red; font-weight: bold; font-size:12pt"> Задача 2. Условие</span>

In [119]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

In [125]:
# Найдите ранг системы векторов v1, v2, v3, v4.

A = np.array([v1,v2,v3,v4])
rank = np.linalg.matrix_rank(A)
rank

4

In [126]:
gram = A@A.T
gram

array([[360,  96,  73, -35],
       [ 96,  46,  16,   4],
       [ 73,  16,  33,   4],
       [-35,   4,   4,  51]])

In [127]:
# Найдите определитель матрицы Грама системы v1, v2, v3, v4.
np.linalg.det(gram)

3716647.9999999995

In [128]:
# Найдите обратную матрицу к матрице Грама системы v1, v2, v3, v4.
np.linalg.inv(gram)

array([[ 0.01711488, -0.02798543, -0.02623063,  0.01599775],
       [-0.02798543,  0.071967  ,  0.03031441, -0.02722776],
       [-0.02623063,  0.03031441,  0.07683106, -0.02640498],
       [ 0.01599775, -0.02722776, -0.02640498,  0.03479318]])